import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '@/components/Header';
import { NextSSRPlugin } from '@uploadthing/react/next-ssr-plugin';
import { extractRouterConfig } from 'uploadthing/server';
import { ourFileRouter } from '@/app/api/uploadthing/core';
import { cn } from '@/lib/utils';
import Toast from '@/components/Toast';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Todo',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={'h-full'}>
      <body className={cn(inter.className, 'flex-col flex h-full')}>
        <Header />
        {children}
        <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
        <Toast />
      </body>
    </html>
  );
}
